name: Azure Static Web Apps CI

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: staging
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: |
          npm install

      - name: Run unit tests
        run: |
          npm run test:unit 

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:
            ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_ISLAND_01BE9BF1E
            }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          deployment_environment: 'staging'
          # For information on SWA workflow configurations: https://aka.ms/swaworkflowconfig
          app_location: '/'
          output_location: 'dist' # Built app content directory - optional
        env:
          VITE_AUTH_CLIENT_ID: ${{ vars.VITE_AUTH_CLIENT_ID }}
          VITE_AUTH_AUTHORITY: ${{ vars.VITE_AUTH_AUTHORITY }}
          VITE_AUTH_REDIRECT_URI: ${{ vars.VITE_AUTH_REDIRECT_URI }}

      # Step 5: Post the deployed URL to GitHub Actions summary
      - name: Post URL
        run: |
          echo "App deployed :rocket:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.builddeploy.outputs.static_web_app_url }} >> $GITHUB_STEP_SUMMARY
