name: Azure Static Web Apps CI

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Integration Job
    environment: staging
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies
        run: |
          npm install

      - name: Linting
        run: |
          npm run lint

      - name: Run unit tests
        run: |
          npm run test:unit

      - name: Build 
        run: |
          npm run build

      - name: Show summary
        run: |
          echo "App built :rocket:" >> $GITHUB_STEP_SUMMARY
