name: Sync Version Tag

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  sync-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get package version
      id: package-version
      run: |
        # Extract version from package.json
        VERSION=$(node -p "require('./package.json').version")
        echo "PACKAGE_VERSION=v$VERSION" >> $GITHUB_OUTPUT

    - name: Check if tag exists
      id: check-tag
      run: |
        # Check if the tag already exists
        if git show-ref --tags | grep -q "refs/tags/${{ steps.package-version.outputs.PACKAGE_VERSION }}"; then
          echo "Tag already exists"
          echo "TAG_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "Tag does not exist"
          echo "TAG_EXISTS=false" >> $GITHUB_OUTPUT
        fi

    - name: Create and push tag
      if: steps.check-tag.outputs.TAG_EXISTS == 'false'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # Create and push the new tag
        git tag ${{ steps.package-version.outputs.PACKAGE_VERSION }}
        git push origin ${{ steps.package-version.outputs.PACKAGE_VERSION }}

    - name: Create GitHub Release
      if: steps.check-tag.outputs.TAG_EXISTS == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.package-version.outputs.PACKAGE_VERSION }}
        generate_release_notes: true